version: '3'
services:
  hk-mysql:
   container_name: hk-mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: footgo
    MYSQL_ROOT_PASSWORD: pwd
    MYSQL_ROOT_HOST: '%'
   ports:
   - "3306:3306"
   restart: always
  
  app:
    restart: always
    build: ./APP
    working_dir: /
    ports:
      - "8081:8080"
#    command: mvn clean spring-boot:run
    depends_on:
      - hk-mysql